name: Basic Spring Boot CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Specify the Java distribution
          java-version: '17'

      - run: mvn install
